### ISSUE TITLE
more basic script example.

### ISSUE THREAD

**Issue by nedoskiv** [bondrogeen/web-server#2]
First I want to say, thanks for your wonderful code, 
I'm a bit old style programmer, if it possible to post a simple example (without JSON and JAVASCRIPT) will be nice.
Simple form in one file and form handler (in another file) who just display what is entered in the form as _GET and _POST parameters (variables).

**Comment by bondrogeen** [comment]
Using simple forms, there will be restrictions. since sending the form requires a reload of the page.
And so I recommend using JS to send forms or manage ESP.
But sending simple forms is possible.
You can do it this way.

<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <title>Форма</title>
 </head>
 <body>
  <form id="auth" action="example.lua" method="post"></form>
  <p>...</p>
  <p><input name="login" form="auth">
  <input name="pass" type="password" form="auth"></p>
  <p><input type="submit" form="auth"></p> 
 </body>
</html>

example.html
___________________________________________________________________

return function (args) 
 print(args.login)
 print(args.pass)   
 return '<script> history.back() </script>'  -- 
end

example.lua

What do you want to send in the form?
Maybe I'll tell you how it's easier to do with JavaScript.

**Comment by nedoskiv** [comment]
Thank you, I will check it out myself, but as long as I examined your HTML/JAVASCRIPT/LUA code (not simple_form)
I got to conclusion that authentication is not server based, it is most likely javascript based and probably can be bypassed by someone with little more programing skills in java than mine.

**Comment by nedoskiv** [comment]
and another how to access request variable inside html file using lua code:

```
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Settings page</title></head><body><pre>
<?lua return req.init ?>
</pre>
```
tried that, but it is not working

**Comment by bondrogeen** [comment]
Http basic authentication is also not secure.
You can hack everything. )))
I decided to use Form-based authentication, as there are more possibilities than Http basic authentication.
ESP is limited in resources, and have to sacrifice something.
bug in authentication know, I'll fix it later.

**Comment by nedoskiv** [comment]
yes it is very limited, I hope your server consume less memory than currently used one by me. But what about my second questions about how to access req variable array  into lua code inside HTML file.

**Comment by bondrogeen** [comment]
https://github.com/bondrogeen/NodeMCU-modules
