### ISSUE TITLE
possible memory issue

### ISSUE THREAD

**Issue by nedoskiv** [bondrogeen/web-server#3]
Hello, I'm gonna try to develop an RFID system and start looking for a proper web server, your server is great to serve static files, but after I examined the code believe it gonna fail (out of memory) if lua script is generating dynamic web content. When it sends static files, split them on 1k portions to avoid "out of memory" but if I use a lua script there is nothing that gonna prevent that. Can you implement a function or something that can be used inside lua script to send data to web client in portions to minimize memory usage?

**Comment by bondrogeen** [comment]
Can I look at your code?

**Comment by nedoskiv** [comment]
[web_main.zip](https://github.com/bondrogeen/web-server/files/1741158/web_main.zip)

this is from one of my last projects (using different web server). Take look at the while part, it can generate really large content.... I believe in your server that gonna consume all the memory and cause device to reboot. Gonna test it in few days and tell you the result.

**Comment by bondrogeen** [comment]
I need code where you have problems with my "web server" memory overflow.
Describe your task, maybe I'll tell you how to do it better.
Due to the limited resources of ESP, I was making an emphasis on using JavaScript.
Take the data from ESP and process it with JavaScript.
Try to shift all dynamics to JavaScript.

Имам нужда от код, където имате проблеми с препълването на паметта ми "web server".
Опишете задачата си, може би ще ви кажа как да го направите по-добре.
Поради ограничените ресурси на ESP, аз поставях акцент върху използването на JavaScript.
Вземете данните от ESP и ги обработвайте с JavaScript.
Опитайте се да промените цялата динамика на JavaScript.

**Comment by bondrogeen** [comment]
Look at my examples.

https://github.com/bondrogeen/esp.tda7313
https://github.com/bondrogeen/esp.clock

**Comment by nedoskiv** [comment]
Thank you for response, I'm old style programmer and I know if I let javascript make decisions and logic, my project gonna become insecure. Usually I use javascript for simple task and let server side handle logic etc......
That keep my javascript knowledge low. Guess gonna find a way to make this work somehow.

**Comment by nedoskiv** [comment]
Can I speak with you in kind of chat. If you are interested we can do my next project together, with your javascript programming skills it gonna be easier. I plan to do RFID system for access control. I already do it with a controller mode (ESP just supply data to server and it decide what to do), but want to make it as standalone device. If you are interested email me with some live chat details. My email is: v_armenchev@yahoo.com
